// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT COUNT(*) > 0
FROM users
WHERE email = $1
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT COUNT(*) > 0
FROM users
WHERE username = $1
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUsernameExists, username)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, created_at, updated_at, email, hashed_password)
VALUES (
    gen_random_uuid(), $1, NOW(), NOW(), $2, $3
)
RETURNING id, username, created_at, updated_at, email, hashed_password, art_style, profile_picture
`

type CreateUserParams struct {
	Username       string
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.ArtStyle,
		&i.ProfilePicture,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, created_at, updated_at, hashed_password, art_style, profile_picture
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID             uuid.UUID
	Email          string
	Username       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
	ArtStyle       sql.NullString
	ProfilePicture sql.NullString
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.ArtStyle,
		&i.ProfilePicture,
	)
	return i, err
}

const updateUserLogoutTimestamp = `-- name: UpdateUserLogoutTimestamp :exec
UPDATE users
SET updated_at = NOW()
WHERE username = $1
`

func (q *Queries) UpdateUserLogoutTimestamp(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, updateUserLogoutTimestamp, username)
	return err
}
